# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.11.1'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Init packages'

- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'test.yml'

- script: |
    mv $(Agent.TempDirectory)/.env ./.env
    mv $(Agent.TempDirectory)/test.yml ./test.yml
    npm run test-prod
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: false

- script: |
    npm run build
    npm run package 
  displayName: 'Build and Package'


